# Generated by Django 5.1.3 on 2024-11-12 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('spot_name', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('free', models.PositiveIntegerField()),
                ('parking', models.BooleanField(default=False, verbose_name='')),
                ('baby_station', models.BooleanField(default=False, verbose_name='')),
                ('other', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.countries')),
            ],
        ),
    ]
