# Generated by Django 5.1.3 on 2024-11-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='country',
            field=models.CharField(choices=[('1', '千種区'), ('2', '東区'), ('3', '北区'), ('4', '西区'), ('5', '中村区'), ('6', '中区'), ('7', '昭和区'), ('8', '瑞穂区'), ('9', '熱田区'), ('10', '中川区'), ('11', '港区'), ('12', '南区'), ('13', '守山区'), ('14', '緑区'), ('15', '名東区'), ('16', '天白区')], max_length=100),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='create_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='baby_station',
            field=models.CharField(choices=[('1', 'おむつ台・授乳室あり'), ('2', 'おむつ台あり'), ('3', '授乳室あり'), ('4', 'なし'), ('5', '不明')], max_length=50),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='free',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='other',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='parking',
            field=models.CharField(choices=[('1', 'あり(無料)'), ('2', 'あり(有料)'), ('3', 'なし'), ('4', '不明')], max_length=10),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='spot_name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
    ]
