# Generated by Django 5.1.3 on 2024-11-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postmodel_country_postmodel_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='free',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
