# Generated by Django 5.1.3 on 2024-11-15 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_postmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('free', models.PositiveIntegerField(blank=True, null=True)),
                ('parking', models.CharField(choices=[('1', 'あり(無料)'), ('2', 'あり(有料)'), ('3', 'なし'), ('4', '不明')], max_length=10)),
                ('baby_station', models.CharField(choices=[('1', 'おむつ台・授乳室あり'), ('2', 'おむつ台あり'), ('3', '授乳室あり'), ('4', 'なし'), ('5', '不明')], max_length=50)),
                ('other', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(null=True)),
                ('update_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='PostCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('1', '千種区'), ('2', '東区'), ('3', '北区'), ('4', '西区'), ('5', '中村区'), ('6', '中区'), ('7', '昭和区'), ('8', '瑞穂区'), ('9', '熱田区'), ('10', '中川区'), ('11', '港区'), ('12', '南区'), ('13', '守山区'), ('14', '緑区'), ('15', '名東区'), ('16', '天白区')], max_length=100)),
            ],
            options={
                'db_table': 'post_country',
            },
        ),
        migrations.CreateModel(
            name='PostPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='image/')),
                ('oder', models.IntegerField()),
            ],
            options={
                'db_table': 'post_image',
                'ordering': ['oder'],
            },
        ),
        migrations.DeleteModel(
            name='PostModel',
        ),
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.postcountry'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.postpictures'),
        ),
    ]
