# Generated by Django 5.1.3 on 2024-11-16 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_image_alter_postpictures_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.postpictures'),
        ),
        migrations.AlterField(
            model_name='postpictures',
            name='image',
            field=models.FileField(upload_to='image/'),
        ),
    ]
