# Generated by Django 5.1.3 on 2024-11-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_image_alter_postpictures_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='country',
            new_name='country_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image_id',
        ),
    ]
