# Generated by Django 5.1.3 on 2024-11-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rename_country_post_country_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image_id',
            new_name='image',
        ),
    ]
