# Generated by Django 5.1.3 on 2024-11-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_country_id_post_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postpictures',
            options={},
        ),
        migrations.RemoveField(
            model_name='postpictures',
            name='oder',
        ),
    ]
