# Generated by Django 5.1.3 on 2024-11-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_postpictures_options_remove_postpictures_oder'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
