# Generated by Django 5.1.3 on 2024-11-19 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
