# Generated by Django 5.1.3 on 2024-11-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_create_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_user',
            new_name='user',
        ),
    ]
