# Generated by Django 5.1.3 on 2024-11-19 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_rename_create_user_post_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postcountry',
            table=None,
        ),
        migrations.AlterModelTable(
            name='postpictures',
            table=None,
        ),
    ]
