# Generated by Django 5.1.3 on 2024-11-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_postcountry_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpictures',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
