# Generated by Django 5.1.3 on 2024-11-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_postpictures_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcountry',
            name='country',
            field=models.CharField(choices=[('1', '千種区'), ('2', '東区'), ('3', '北区'), ('4', '西区'), ('5', '中村区'), ('6', '中区'), ('7', '昭和区'), ('8', '瑞穂区'), ('9', '熱田区'), ('10', '中川区'), ('11', '港区'), ('12', '南区'), ('13', '守山区'), ('14', '緑区'), ('15', '名東区'), ('16', '天白区')], max_length=100),
        ),
    ]
