# Generated by Django 5.1.3 on 2024-12-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_postpictures_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpictures',
            name='oder',
            field=models.IntegerField(default=0),
        ),
    ]
