# Generated by Django 5.1.3 on 2024-12-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_postpictures_oder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpictures',
            name='oder',
            field=models.IntegerField(null=True),
        ),
    ]
